export { composeApplication } from './CompositionRoot'
export { createProviderSet } from './ProviderFactory'
export { resolveBackend, DEFAULT_BACKEND } from './ProviderConfig'
export type { ProviderBackend, ProviderSet, AppConfig } from './ProviderConfig'
export type { ApplicationApi } from './CompositionRoot'
