export { DashboardPage } from './DashboardPage'
export { SalesDirectorWorkspace } from './SalesDirectorWorkspace'
export { AccountantWorkspace } from './AccountantWorkspace'
export { WarehouseManagerWorkspace } from './WarehouseManagerWorkspace'
export { PurchasingManagerWorkspace } from './PurchasingManagerWorkspace'
export { SecretaryWorkspace } from './SecretaryWorkspace'
export { SecurityWorkspace } from './SecurityWorkspace'
export { BuffetWorkspace } from './BuffetWorkspace'
export { DataEntryWorkspace } from './DataEntryWorkspace'
export { CollectorWorkspace } from './CollectorWorkspace'
export { DeliveryWorkspace } from './DeliveryWorkspace'
export { ExecutiveOperationsWorkspace } from './ExecutiveOperationsWorkspace'

